{% set name = "cf_xarray" %}
{% set version = "0.7.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5d66504b0c30611efeec54577f7e829fc913b77479da0a50ca8ef967cade6271

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8
    - pip
    - setuptools >=41.2
    - setuptools-scm
  run:
    - python >=3.8
    - xarray

test:
  imports:
    - cf_xarray
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/xarray-contrib/cf-xarray
  license: Apache-2.0
  license_file: LICENSE
  summary: A lightweight convenience wrapper for using CF attributes on xarray objects.

  description: |
    A lightweight convenience wrapper for using CF attributes on xarray objects..
  doc_url: https://cf-xarray.readthedocs.io/
  dev_url: https://github.com/xarray-contrib/cf-xarray

extra:
  recipe-maintainers:
    - dcherian
    - malmans2
