{% set name = "cf_xarray" %}
{% set version = "0.6.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 25097a813fbf484d23e7cd3833b2677d38d52e69d09d39a0068b82ade7271245

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools >=41.2
    - setuptools-scm
  run:
    - python >=3.6
    - numpy >=1.15
    - pandas >=0.25
    - setuptools >=41.2
    - xarray

test:
  imports:
    - cf_xarray
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/xarray-contrib/cf-xarray
  license: Apache-2.0
  license_file: LICENSE
  summary: A lightweight convenience wrapper for using CF attributes on xarray objects.

  description: |
    A lightweight convenience wrapper for using CF attributes on xarray objects..
  doc_url: https://cf-xarray.readthedocs.io/
  dev_url: https://github.com/xarray-contrib/cf-xarray

extra:
  recipe-maintainers:
    - dcherian
    - malmans2
