{% set name = "cf_xarray" %}
{% set version = "0.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9d997f9ee7d7fa3153fecaafad5b41e73e0ff9e55713388cdd2fdaa53cd290fb

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
    - setuptools_scm
  run:
    - xarray
    - python >=3.6

test:
  imports:
    - cf_xarray
  requires:
    - pytest

about:
  home: https://github.com/xarray-contrib/cf-xarray
  license: Apache-2.0
  license_file: LICENSE
  summary: A lightweight convenience wrapper for using CF attributes on xarray objects.

  description: |
    A lightweight convenience wrapper for using CF attributes on xarray objects..
  doc_url: https://cf-xarray.readthedocs.io/
  dev_url: https://github.com/xarray-contrib/cf-xarray

extra:
  recipe-maintainers:
    - dcherian
